### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by puppykickr** [CaptainDaVinci/Music-DL#7]
The app will not work due to recent changes by Youtube.

**Comment by CaptainDaVinci** [comment]
Hi @puppykickr, this app relies heavily on `youtube-dl` and ec2 instance on aws, right now the ec2 instance has expired hence the error. But `youtube-dl` still continues to work.

**Comment by puppykickr** [comment]
@CaptainDaVinci 

Well, then I guess that you and I have different ideas about what the term 'not working' means.

Does the apk download?
yes.

Does the apk install, and open?
yes, and yes.

Does the app download anything?
no.

![Screenshot_2020-07-29_11-12-48](https://user-images.githubusercontent.com/44860287/88824875-811cdb00-d18c-11ea-8e01-daebe4638318.jpg)

**Comment by CaptainDaVinci** [comment]
@puppykickr  As I said, that's cause the server which hosts all the processing tasks has expired. But that doesn't mean you can no longer do what this app does, [youtube-dl](https://github.com/ytdl-org/youtube-dl) still works fine.

P.S: The server expired recently and I forgot to update the Readme file.

**Comment by CaptainDaVinci** [comment]
What I meant by my first comment was that changes to YouTube did not lead to this app not working, the error is because it's pinging a server which no longer exists.

**Comment by puppykickr** [comment]
It does not change the fact that the app will not download.

The purpose of the app appears to be downloading.

If the app will not download, then it is not working.

Grant Ryan Swan
   (puppykicker)

**Comment by CaptainDaVinci** [comment]
Eh, I never mentioned that the app is working currently. Just pointed out that changes in YouTube did not affect the core logic behind the app - since that's what you had originally posted.

But thanks for your input @puppykickr, I've updated the readme to caution anyone who comes across this repo.
